---
blank_issues_enabled: false
contact_links:
  - name: ManagedIdentityPermissionManager Community Support
    url: https://github.com/michaelmsonne/ManagedIdentityPermissionManager/discussions
    about: Please ask and answer questions here.
